-- Database schema for PokéMart (CS 316 Mini-Amazon project).
-- Tables are ordered by dependency: referenced tables are created before
-- tables that reference them so foreign key constraints resolve correctly.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(320) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    balance DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    address VARCHAR(255) NOT NULL
);

-- Self-referential hierarchy: parent_id = NULL means root category.
-- UNIQUE(name, parent_id) prevents duplicate sibling names while allowing
-- the same name to appear under different parents (e.g. two "Accessories").
CREATE TABLE Categories (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    parent_id INT REFERENCES Categories(id),
    slug VARCHAR(255) UNIQUE NOT NULL,   -- URL-safe identifier for routes
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE(name, parent_id)
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    creator_id INT NOT NULL REFERENCES Users(id),
    category_id INT NOT NULL REFERENCES Categories(id),
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT,
    available BOOLEAN DEFAULT TRUE
);

CREATE TABLE Tags (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    display_name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    created_by INT REFERENCES Users(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ProductTags (
    product_id INT NOT NULL REFERENCES Products(id) ON DELETE CASCADE,
    tag_id INT NOT NULL REFERENCES Tags(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, tag_id)
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Inventory (
    seller_id INT NOT NULL REFERENCES Users(id),
    product_id INT NOT NULL REFERENCES Products(id),
    quantity INT NOT NULL CHECK (quantity >= 0),
    price DECIMAL(12,2) NOT NULL CHECK (price >= 0),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (seller_id, product_id)
);

-- One review per (user, product) pair enforced by the UNIQUE constraint;
-- upserts use ON CONFLICT (user_id, product_id) DO UPDATE to allow edits.
CREATE TABLE ProductReviews (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    product_id INT NOT NULL REFERENCES Products(id),
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    review TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    UNIQUE (user_id, product_id)
);

CREATE TABLE SellerReviews (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    seller_id INT NOT NULL REFERENCES Users(id),
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    review TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    UNIQUE (user_id, seller_id)
);

CREATE INDEX idx_product_reviews_product_created_at
ON ProductReviews(product_id, created_at DESC);

CREATE INDEX idx_product_reviews_user_created_at
ON ProductReviews(user_id, created_at DESC);

CREATE INDEX idx_seller_reviews_seller_created_at
ON SellerReviews(seller_id, created_at DESC);

CREATE INDEX idx_seller_reviews_user_created_at
ON SellerReviews(user_id, created_at DESC);

-- Composite PK (user_id, product_id, seller_id) instead of a SERIAL id:
-- enforces at most one row per buyer-product-seller combination, so adding
-- the same item again hits ON CONFLICT and increments quantity rather than
-- inserting a duplicate row.  unit_price snapshots the seller's price at
-- add-time so the cart reflects what the buyer originally saw even if the
-- seller later changes the price.  saved=TRUE moves an item to "Save for
-- Later" without deleting the row; only saved=FALSE items are checked out.
CREATE TABLE cart_items (
    user_id INT NOT NULL REFERENCES Users(id),
    product_id INT NOT NULL REFERENCES Products(id),
    seller_id INT NOT NULL REFERENCES Users(id),
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price DECIMAL(12,2) NOT NULL CHECK (unit_price >= 0),
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    saved BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (user_id, product_id, seller_id)
);

-- fulfilled is derived, not set directly: the seller fulfillment transaction
-- sets it to TRUE automatically when the last pending line item is fulfilled.
-- cancelled follows the reverse pattern: set to TRUE by the cancellation
-- transaction only after verifying no line items have been fulfilled yet.
CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES Users(id),
    total_amount DECIMAL(12,2) NOT NULL,
    num_items INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fulfilled BOOLEAN NOT NULL DEFAULT FALSE,
    cancelled BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE order_items (
    id SERIAL PRIMARY KEY,
    order_id INT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id INT NOT NULL REFERENCES Products(id),
    seller_id INT NOT NULL REFERENCES Users(id),
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price DECIMAL(12,2) NOT NULL CHECK (unit_price >= 0),
    fulfilled BOOLEAN NOT NULL DEFAULT FALSE,
    fulfilled_at TIMESTAMP,
    UNIQUE (order_id, product_id, seller_id)
);

CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_orders_user_status_created_at ON orders(user_id, cancelled, fulfilled, created_at DESC);
CREATE INDEX idx_order_items_seller_order ON order_items(seller_id, order_id, fulfilled, id);
CREATE INDEX idx_order_items_product_order ON order_items(product_id, order_id);

CREATE TABLE wishlist (
    user_id INT NOT NULL REFERENCES Users(id),
    product_id INT NOT NULL REFERENCES Products(id),
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, product_id)
);

CREATE TABLE coupons (
    id SERIAL PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    discount_type VARCHAR(10) NOT NULL CHECK (discount_type IN ('percentage', 'flat')),
    discount_value DECIMAL(12,2) NOT NULL CHECK (discount_value > 0),
    min_order_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    max_uses INT,
    expiry_date TIMESTAMP,
    applicable_product_id INT REFERENCES Products(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE coupon_uses (
    id SERIAL PRIMARY KEY,
    coupon_id INT NOT NULL REFERENCES coupons(id),
    user_id INT NOT NULL REFERENCES Users(id),
    order_id INT NOT NULL REFERENCES orders(id),
    used_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_categories_parent_id ON Categories(parent_id);
CREATE INDEX idx_product_tags_tag_id ON ProductTags(tag_id);
-- Partial index (WHERE quantity > 0) covers the exact predicate used by the
-- product detail page to list available sellers ordered by price, so the
-- planner satisfies that query entirely from the index without touching
-- out-of-stock rows in the heap.
CREATE INDEX idx_inventory_product_instock_price_qty ON Inventory(product_id, price ASC, quantity DESC, seller_id) WHERE quantity > 0;
CREATE INDEX idx_cart_items_user_saved_added_at ON cart_items(user_id, saved, added_at DESC);
CREATE INDEX idx_purchases_uid_time_desc ON Purchases(uid, time_purchased DESC);
CREATE INDEX idx_wishlist_user_added_at_desc ON wishlist(user_id, added_at DESC);
CREATE INDEX idx_coupon_uses_coupon_id ON coupon_uses(coupon_id);
